export const testData = {
  baseUrl: "https://parabank.parasoft.com/parabank/index.htm",
  username: "ok652",
  password: "Surekha@123",
  dataSheetRows: [
  {
    "FirstName": "Om",
    "LastName": "Korde",
    "Address": "145 vlvnfp Street",
    "City": "Delhi",
    "State": "KA",
    "Zip Code": "752789",
    "Phone": "1469272392",
    "SSN": "300984098",
    "Username": "omKorde72",
    "Password": "GikZKRWcoe",
    "Confirm": "GikZKRWcoK"
  },
  {
    "FirstName": "Vivaan",
    "LastName": "Mishra",
    "Address": "239 mGAoVl Street",
    "City": "Pune",
    "State": "TN",
    "Zip Code": "649085",
    "Phone": "5127197786",
    "SSN": "247809126",
    "Username": "vivaanmishra57",
    "Password": "imoNWecEAO",
    "Confirm": "imoNWecEAO"
  },
  {
    "FirstName": "Rohan",
    "LastName": "Pandey",
    "Address": "89 JpAZzF Street",
    "City": "Mumbai",
    "State": "TN",
    "Zip Code": "336474",
    "Phone": "7979648011",
    "SSN": "646223476",
    "Username": "rohanpandey96",
    "Password": "wVcfkAaAUT",
    "Confirm": "wVcfkAaAUT"
  },
  {
    "FirstName": "Aditya",
    "LastName": "Deshmukh",
    "Address": "157 rjaYpT Street",
    "City": "Hyderabad",
    "State": "MH",
    "Zip Code": "318985",
    "Phone": "1502543783",
    "SSN": "141746142",
    "Username": "adityadeshmukh78",
    "Password": "CtrsBoOhlR",
    "Confirm": "CtrsBoOhlR"
  },
  {
    "FirstName": "Reyansh",
    "LastName": "Deshmukh",
    "Address": "172 ctWsXy Street",
    "City": "Mumbai",
    "State": "GJ",
    "Zip Code": "095485",
    "Phone": "1749948876",
    "SSN": "361238450",
    "Username": "reyanshdeshmukh14",
    "Password": "LwLxkGYwtT",
    "Confirm": "LwLxkGYwtT"
  },
  {
    "FirstName": "Reyansh",
    "LastName": "Khan",
    "Address": "158 LpPlJu Street",
    "City": "Delhi",
    "State": "GJ",
    "Zip Code": "663753",
    "Phone": "1759389016",
    "SSN": "198393439",
    "Username": "reyanshkhan74",
    "Password": "uxEadcNHzK",
    "Confirm": "uxEadcNHzK"
  },
  {
    "FirstName": "Ishaan",
    "LastName": "Mishra",
    "Address": "247 LDDVdT Street",
    "City": "Nashik",
    "State": "TS",
    "Zip Code": "986462",
    "Phone": "6002554281",
    "SSN": "153820223",
    "Username": "ishaanmishra25",
    "Password": "vREpsdGDus",
    "Confirm": "vREpsdGDus"
  },
  {
    "FirstName": "Vivaan",
    "LastName": "Khan",
    "Address": "295 EAnvXx Street",
    "City": "Pune",
    "State": "TS",
    "Zip Code": "738596",
    "Phone": "8208279306",
    "SSN": "455197602",
    "Username": "vivaankhan99",
    "Password": "DmgfxbUIey",
    "Confirm": "DmgfxbUIey"
  },
  {
    "FirstName": "Aditya",
    "LastName": "Pandey",
    "Address": "88 loonmU Street",
    "City": "Nashik",
    "State": "RJ",
    "Zip Code": "483210",
    "Phone": "9001517198",
    "SSN": "125941622",
    "Username": "adityapandey84",
    "Password": "fWxhhblWPe",
    "Confirm": "fWxhhblWPe"
  }
],
};